### ISSUE TITLE
1.2.1 breaks usage of path modifiers

### ISSUE THREAD

**Issue by SkyleLai** [strapi-community/strapi-plugin-local-image-sharp#12]
I update to 1.2.1 and get 404 using path modifiers.
e.g. http://localhost:1337/uploads/w_200/buffalo_56442f4096.png

I tried to create a new project and get same error too.
strapi version: 4.4.3

Using query parameters modifiers(1.2.1) or 1.2.0 works fine, btw.

**Comment by rafaeljesusaraiva** [comment]
Same here... Using path modifiers leads to a 404 return.

`{"data":null,"error":{"status":404,"name":"NotFoundError","message":"Not Found","details":{}}}`

**Comment by AndrewTannerNA** [comment]
I'm also seeing this issue with 1.2.1 running on Strapi 4.5.4:

`{"data":null,"error":{"status":404,"name":"NotFoundError","message":"Not Found","details":{}}}`

Do the maintainers intend to look at this issue? Unfortunately I am not experienced with Node.js apps so cannot help personally.
