### ISSUE TITLE
Plugin doesnt work

### ISSUE THREAD

**Issue by sanch941** [strapi-community/strapi-plugin-local-image-sharp#2]
Just install plugin with yarn and get image by modifiers returns 'Not found'

**Comment by Sandstedt** [comment]
Make sure the URL you add are correct before injecting the parameters.

Ex if you have a image in your media library named test1.jpg, the url usually looks something like this:
```http://localhost:1337/uploads/test1_686afb340a.jpg```

So with parameters, the url should look like this:
```http://localhost:1337/uploads/s_400x400/test1_686afb340a.jpg```

**Comment by stafyniaksacha** [comment]
Should be fixed by https://github.com/strapi-community/strapi-plugin-local-image-sharp/pull/14 on `v1.3.0`, please reopen if the issue still occurs
