### ISSUE TITLE
Cache images?

### ISSUE THREAD

**Issue by ohbob** [strapi-community/strapi-plugin-local-image-sharp#3]
Is there a way once requested the image is being cached forever? I don't want to regenerate the image on each call. 

```<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
        <img alt="image" src="http://localhost:1337/uploads/f_avif,q_70,w_920/F_Sp8o_KVIAA_0_U7b_bc59f01efd.jpg">
</body>
</html>
```

**Comment by Sandstedt** [comment]
Yes. Set a cache rule one your server.

**Comment by ohbob** [comment]
> Yes. Set a cache rule on your server.

Could you give an example please?

**Comment by Sandstedt** [comment]
Ngnix:
https://linuxhint.com/cache-static-resources-https-nginx/

Apache:
https://www.faqforge.com/linux/enable-image-caching-in-apache-for-better-google-page-speed-results/

**Comment by Sandstedt** [comment]
There is also cache settings you can change in next.config.js to ex change the cache duration. If you have no cache on the server, and haven't set minimumCacheTTL, then you images will get thrown away as soon as they have been generated.

https://nextjs.org/docs/api-reference/next/image#caching-behavior

**Comment by ohbob** [comment]
do i understand this right, the caching is happening on the client side for the front end? If that's the case, seems a bit odd, that it's not being cached at backend..

**Comment by Sandstedt** [comment]
Oh sorry, mixed together this issue with a next/image thread I'm getting a lot of updates on. Edited.

**Comment by Sandstedt** [comment]
But I would recommending using a cache layer in front of this plugin. Wouldn't not expect that's in the scope of this plugin, it has just a single purpose, to generate an images based on the parameters I send to it. See it like a microservice. Cause caching all depends on the rest of the setup in your project. If your using something like Gatsby or Next.js, it will be build into the framework.

**Comment by c3s4** [comment]
> it has just a single purpose, to generate an images based on the parameters I send to it
The generated image is not saved in the filesystem, am I right?

Thanks

**Comment by stafyniaksacha** [comment]
You can now set `maxAge` properly in the plugin setting.
Before `v1.2.0` this setting were not used by ipx, it was fixed on https://github.com/unjs/ipx/pull/71 so browser cache should now work as expected!

About server side caching, for now images are not stored anywhere.
We can extend https://github.com/strapi-community/strapi-plugin-rest-cache to allow caching assets?

**Comment by ohbob** [comment]
please extend serverside caching of images

**Comment by KevinChassagne** [comment]
+1 is this something planned in the future?

**Comment by ohbob** [comment]
> browser

Any progress on this? I really want this to become a reality) how can I help?

**Comment by ohbob** [comment]
> You can now set `maxAge` properly in the plugin setting.
> Before `v1.2.0` this setting were not used by ipx, it was fixed on https://github.com/unjs/ipx/pull/71 so browser cache should now work as expected!
> 
> About server side caching, for now images are not stored anywhere.
> We can extend https://github.com/strapi-community/strapi-plugin-rest-cache to allow caching assets?

Any progress on this? I really want this to become a reality) how can I help?

**Comment by stafyniaksacha** [comment]
I do not have to much time to work on this for now, sorry!
If someone could open a PR I will take time to review/publish, that would be appreciated.

**Comment by stafyniaksacha** [comment]
Hello there!

The feature is done in `v1.4.0`: https://strapi-community.github.io/strapi-plugin-local-image-sharp/guide/#configuration

Also, the new documentation is online! Feedback is welcome!

**Comment by martin-landhi** [comment]
How do you manage when you change the image? because the reiszed images are cached and not change. How can i flush that specific image cache?
